# Generated by Django 2.2 on 2020-11-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='portada_picture',
            field=models.ImageField(default='images/default-portada.png', upload_to='images/profile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='images/default-profile.png', upload_to='images/profile/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
