# Generated by Django 2.2 on 2020-11-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201108_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='portada_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
